// Founder responsibilities supplied by 3T Station.
export const founders = [
  {
    id: "muiz",
    name: "Muiz",
    role: "Marketing & Operations Executive",
    business: "Game top-up",
    description: "Muiz leads the game top-up business and handles marketing and operations, helping customers find their next in-game top-up.",
    image: "/images/founders/muiz.jpg",
    width: 602,
    height: 1080,
    href: "/topup",
    linkLabel: "Explore game top-ups",
  },
  {
    id: "sidqi",
    name: "Sidqi",
    role: "Administrative & Accounts Executive",
    business: "Phone repair",
    description: "Sidqi looks after the phone repair business alongside company administration and accounts, helping customers take the next step in caring for their devices.",
    image: "/images/founders/sidqi.png",
    width: 1024,
    height: 1536,
    href: "/repair",
    linkLabel: "Explore phone repair",
  },
  {
    id: "syabil",
    name: "Syabil",
    role: "Manager",
    business: "Fresh yogurt",
    description: "Syabil manages 3T Station and leads the yogurt business, bringing a sweet touch to the station with mango, blueberry, and strawberry yogurt sticks.",
    image: "/images/founders/syabil.png",
    width: 936,
    height: 1680,
    href: "/#yogurt",
    linkLabel: "Explore our yogurt",
  },
];
